# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD001 - Heading levels should only increment by one level at a time
MD001: true

# MD003 - Heading style
MD003:
  style: atx

# MD004 - Unordered list style
MD004:
  style: dash

# MD005 - Inconsistent indentation for list items
MD005: true

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD009 - Trailing spaces
MD009:
  br_spaces: 2
  list_item_empty_lines: false

# MD010 - Hard tabs
MD010:
  code_blocks: false

# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013 - Line length (disabled - often unavoidable in technical docs)
MD013: false

# MD014 - Dollar signs used before commands without showing output
MD014: false

# MD022 - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024 - Multiple headings with the same content
MD024:
  siblings_only: true

# MD025 - Multiple top-level headings
MD025: true

# MD026 - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!?"

# MD029 - Ordered list item prefix
MD029:
  style: one

# MD030 - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD031 - Fenced code blocks should be surrounded by blank lines
MD031: true

# MD032 - Lists should be surrounded by blank lines
MD032: true

# MD033 - Inline HTML (disabled - sometimes needed)
MD033: false

# MD034 - Bare URL used
MD034: true

# MD035 - Horizontal rule style
MD035:
  style: "---"

# MD036 - Emphasis used instead of a heading
MD036: false

# MD037 - Spaces inside emphasis markers
MD037: true

# MD038 - Spaces inside code span elements
MD038: true

# MD039 - Spaces inside link text
MD039: true

# MD040 - Fenced code blocks should have a language specified
MD040: true

# MD041 - First line should be a top-level heading (disabled for generated files)
MD041: false

# MD042 - No empty links
MD042: true

# MD044 - Proper names should have correct capitalization
MD044:
  names:
    - Terraform
    - HashiCorp
    - F5
    - GitHub
  code_blocks: false

# MD045 - Images should have alt text
MD045: true

# MD046 - Code block style
MD046:
  style: fenced

# MD047 - Files should end with a single newline character
MD047: true

# MD048 - Code fence style
MD048:
  style: backtick

# MD049 - Emphasis style
MD049:
  style: asterisk

# MD050 - Strong style
MD050:
  style: asterisk

# MD051 - Link fragments should be valid
MD051: true

# MD052 - Reference links and images should use a label that is defined
MD052: true

# MD053 - Link and image reference definitions should be needed
MD053: true
