// Copyright (c) Robin Mordasiewicz
// SPDX-License-Identifier: MPL-2.0

// Code generated by tools/generator. DO NOT EDIT.

package ticket_tracking_system

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/robinmordasiewicz/terraform-provider-f5-distributed-cloud/internal/client"
)

var _ resource.Resource = &TicketTrackingSystemResource{}
var _ resource.ResourceWithImportState = &TicketTrackingSystemResource{}

func NewTicketTrackingSystemResource() resource.Resource {
	return &TicketTrackingSystemResource{}
}

type TicketTrackingSystemResource struct {
	client *client.Client
}

type TicketTrackingSystemResourceModel struct {
	ID          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Namespace   types.String `tfsdk:"namespace"`
	Description types.String `tfsdk:"description"`
	Labels      types.Map    `tfsdk:"labels"`
	Annotations types.Map    `tfsdk:"annotations"`
}

type APITicketTrackingSystem struct {
	Metadata struct {
		Name        string            `json:"name"`
		Namespace   string            `json:"namespace,omitempty"`
		Description string            `json:"description,omitempty"`
		UID         string            `json:"uid,omitempty"`
		Labels      map[string]string `json:"labels,omitempty"`
		Annotations map[string]string `json:"annotations,omitempty"`
	} `json:"metadata"`
	Spec map[string]interface{} `json:"spec,omitempty"`
}

func (r *TicketTrackingSystemResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ticket_tracking_system"
}

func (r *TicketTrackingSystemResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Public Custom APIs for Ticket Tracking System related operations",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique identifier of the resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "Name of the resource.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"namespace": schema.StringAttribute{
				Description: "Namespace where the resource will be created.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Description: "Description of the resource.",
				Optional:    true,
			},
			"labels": schema.MapAttribute{
				Description: "Labels for the resource.",
				Optional:    true,
				ElementType: types.StringType,
			},
			"annotations": schema.MapAttribute{
				Description: "Annotations for the resource.",
				Optional:    true,
				ElementType: types.StringType,
			},
		},
	}
}

func (r *TicketTrackingSystemResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T", req.ProviderData))
		return
	}
	r.client = c
}

func (r *TicketTrackingSystemResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data TicketTrackingSystemResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiReq := APITicketTrackingSystem{}
	apiReq.Metadata.Name = data.Name.ValueString()
	apiReq.Metadata.Namespace = data.Namespace.ValueString()
	if !data.Description.IsNull() {
		apiReq.Metadata.Description = data.Description.ValueString()
	}

	var apiResp APITicketTrackingSystem
	path := fmt.Sprintf("/api/web/%s/ticket_tracking_systems", data.Namespace.ValueString())
	if err := r.client.Post(ctx, path, apiReq, &apiResp); err != nil {
		resp.Diagnostics.AddError("Error Creating TicketTrackingSystem",
			fmt.Sprintf("Could not create ticket_tracking_system %s/%s: %s", data.Namespace.ValueString(), data.Name.ValueString(), err))
		return
	}

	data.ID = types.StringValue(apiResp.Metadata.UID)
	if data.ID.ValueString() == "" {
		data.ID = types.StringValue(apiResp.Metadata.Namespace + "/" + apiResp.Metadata.Name)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TicketTrackingSystemResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data TicketTrackingSystemResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var apiResp APITicketTrackingSystem
	path := fmt.Sprintf("/api/web/%s/ticket_tracking_systems/%s", data.Namespace.ValueString(), data.Name.ValueString())
	if err := r.client.Get(ctx, path, &apiResp); err != nil {
		resp.Diagnostics.AddError("Error Reading TicketTrackingSystem",
			fmt.Sprintf("Could not read ticket_tracking_system %s/%s: %s", data.Namespace.ValueString(), data.Name.ValueString(), err))
		return
	}

	data.Name = types.StringValue(apiResp.Metadata.Name)
	data.Namespace = types.StringValue(apiResp.Metadata.Namespace)
	if apiResp.Metadata.Description != "" {
		data.Description = types.StringValue(apiResp.Metadata.Description)
	}
	if apiResp.Metadata.UID != "" {
		data.ID = types.StringValue(apiResp.Metadata.UID)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TicketTrackingSystemResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data TicketTrackingSystemResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiReq := APITicketTrackingSystem{}
	apiReq.Metadata.Name = data.Name.ValueString()
	apiReq.Metadata.Namespace = data.Namespace.ValueString()
	if !data.Description.IsNull() {
		apiReq.Metadata.Description = data.Description.ValueString()
	}

	var apiResp APITicketTrackingSystem
	path := fmt.Sprintf("/api/web/%s/ticket_tracking_systems/%s", data.Namespace.ValueString(), data.Name.ValueString())
	if err := r.client.Put(ctx, path, apiReq, &apiResp); err != nil {
		resp.Diagnostics.AddError("Error Updating TicketTrackingSystem",
			fmt.Sprintf("Could not update ticket_tracking_system %s/%s: %s", data.Namespace.ValueString(), data.Name.ValueString(), err))
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *TicketTrackingSystemResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data TicketTrackingSystemResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	path := fmt.Sprintf("/api/web/%s/ticket_tracking_systems/%s", data.Namespace.ValueString(), data.Name.ValueString())
	if err := r.client.Delete(ctx, path); err != nil {
		resp.Diagnostics.AddError("Error Deleting TicketTrackingSystem",
			fmt.Sprintf("Could not delete ticket_tracking_system %s/%s: %s", data.Namespace.ValueString(), data.Name.ValueString(), err))
		return
	}
}

func (r *TicketTrackingSystemResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
